### ISSUE TITLE
Percentage for translate (100%, 0)

### ISSUE THREAD

**Issue by ghost** [NativeScript/animation-demo#6]
I have tried the ns-css-animation but translate(-100%, 0) worked as 100px;

Is these feature not supported? or coming soon? or am I doing something wrong. Thanks for the awesome framework.

**Comment by vakrilov** [comment]
Percentages are still not supported inside translate - so `100%` gets parsed as 100 pixels.
You propose it in the [NativeScript](https://github.com/NativeScript/NativeScript/issues) repo.
